import AppThemeColors from './AppThemeColors';
const {
  Primary,
  PrimaryDark,
  placeholderTextColor,
  PrimaryTextColor,
  SecondaryTextColor,
  TextInputBorderColor,
  Secondary,
  cardBackground,
  textColor,
  Blue_1,
  Gray_1,
  Gray_2,
  Gray_3,
  Gray_4,
  Gray_5,
  Gray_Text,
  Gray_Placeholder,
  orange,
  Gradient_New,
  switchableButton,
  inActiveSwitchableButtonText,
  textInputBorder,
  orderCardBackground,
  orderCardText,
  black,
  background,
  disabled_textInput,
  disabled_button,
  bottomTabBackground,
} = AppThemeColors;

// Export colors
const Colors = {
  Primary,
  PrimaryDark,
  placeholderTextColor,
  PrimaryTextColor,
  SecondaryTextColor,
  TextInputBorderColor,
  Secondary,
  cardBackground,
  textColor,
  Blue_1,
  Gray_1,
  Gray_2,
  Gray_3,
  Gray_4,
  Gray_5,
  Gray_Text,
  Gray_Placeholder,
  orange,
  Gradient_New,
  switchableButton,
  inActiveSwitchableButtonText,
  textInputBorder,
  orderCardBackground,
  orderCardText,
  black,
  background,
  disabled_textInput,
  disabled_button,
  bottomTabBackground,
};

export default Colors;
